### ISSUE TITLE
migrate bufferd plugin

### ISSUE THREAD

**Issue by y-ken** [fluent-plugins-nursery/fluent-plugin-zabbix-simple#2]
Hi @sunny4381 
How about merge forked plugin? It is nice to unity one plugin.
https://github.com/cy-katsuhiro-miura/fluent-plugin-zabbix-simple/

**Comment by y-ken** [comment]
Could you see this issue? @okkez

**Comment by okkez** [comment]
OK, I wiil check later.

**Comment by okkez** [comment]
Both https://github.com/sunny4381/fluent-plugin-zabbix-simple and https://github.com/cy-katsuhiro-miura/fluent-plugin-zabbix-simple/ depend on [zabbix gem](https://rubygems.org/gems/zabbix). But zabbix gem has been unmaintained since 2011 and Its repository on github.com has gone away.
So we cannot keep maintaining those plugins at all using zabbix gem.
We need to use other library to access zabbix that is keep maintaining actively such as https://github.com/express42/zabbixapi.

I think that https://github.com/cy-katsuhiro-miura/fluent-plugin-zabbix-simple does not work at all because it does not implement `write` method in the buffered output plugin. https://github.com/cy-katsuhiro-miura/fluent-plugin-zabbix-simple is broken plugin.

See also
* http://docs.fluentd.org/v0.10/articles/plugin-development#writing-buffered-output-plugins
* http://docs.fluentd.org/v0.12/articles/plugin-development#writing-buffered-output-plugins

**Comment by sunny4381** [comment]
@y-ken @okkez I have no problems about to merge cy-katsuhiro-miura/fluent-plugin-zabbix-simple. and I have no longer used this plugin. So could you take over maintainer?

**Comment by okkez** [comment]
OK. Could you create new issue on https://github.com/fluent-plugins-nursery/contact ?
I will maintain this plugin on our organization.
